apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: github-sensor-sa
  dependencies:
    - name: github-event
      eventSourceName: github-event-source
      eventName: github-es-svc
  triggers:
    - template:
        name: trigger-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-workflow-
                namespace: workflows
              spec:
                workflowTemplateRef:
                  name: silly-template
